version: "3.8"
services:
  overland-listener:
    build: .
    image: overland-listener:latest
    container_name: overland-listener
    environment:
      INGEST_TOKEN: "${INGEST_TOKEN}"
      AUTH_SECRET: "${AUTH_SECRET}"
      LOG_DIR: /data
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    restart: unless-stopped