version: "3.8"
services:
  overland-listener:
    build: .
    image: overland-listener:latest
    container_name: overland-listener
    environment:
      INGEST_TOKEN: "${INGEST_TOKEN}"
      AUTH_SECRET: "${AUTH_SECRET}"
      STORAGE_BACKEND: "s3"
      S3_BUCKET: "${S3_BUCKET}"
      S3_PREFIX: "${S3_PREFIX}"        # optional
      AWS_REGION: "${AWS_REGION}"      # optional
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"        # or IAM role if on EC2
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_ENDPOINT_URL: "${AWS_ENDPOINT_URL}"
      LOG_DIR: /data
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    restart: unless-stopped